import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

for (const width of [1280, 390]) for (const theme of ["light", "dark"]) test(`focused relationship keeps evidence independent and save explicit at ${width}px in ${theme}`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto("/evidence-fixture/inventory");
  await page.getByRole("banner").getByRole("combobox", { name: "Appearance", exact: true }).selectOption(theme);
  await page.getByRole("button", { name: "Open focused relationship", exact: true }).click();
  const focused = page.getByRole("region", { name: "Example Tool", exact: true });
  await expect(focused.getByRole("heading", { name: "Example Tool", exact: true })).toBeFocused();
  const extras = focused.getByText("Work sample and supporting snapshot (optional)", { exact: true });
  await expect(extras.locator("..")).toHaveJSProperty("open", false);
  await focused.getByText("Inspect extracted claims and correct evidence", { exact: true }).click();
  await focused.getByRole("textbox", { name: "Corrected observation text", exact: true }).fill("Synthetic correction remains separate from relationship decisions.");
  await focused.getByRole("button", { name: "Correct synthetic evidence", exact: true }).click();
  await expect(focused.getByText("Synthetic evidence corrected. No relationship saved.", { exact: true })).toBeVisible();
  await expect(page.getByLabel("Synthetic save operations")).toHaveText("");
  const date = focused.getByLabel("Started using (optional)", { exact: true });
  await expect(date).toHaveValue("");
  await focused.getByRole("button", { name: "Use this observed date as my start date", exact: true }).click();
  await expect(date).toHaveValue("2024-06-03");
  await expect(focused.getByText("Unsaved", { exact: true })).toBeVisible();
  const evidence = focused.getByRole("complementary", { name: "Evidence for Example Tool", exact: true });
  const save = focused.getByRole("button", { name: "Confirm and save privately", exact: true });
  const boxes = await Promise.all([date.boundingBox(), evidence.boundingBox(), save.boundingBox(), extras.boundingBox()]);
  if (width < 760) {
    expect(boxes[1]!.y).toBeGreaterThan(boxes[0]!.y + boxes[0]!.height);
    expect(boxes[2]!.y).toBeGreaterThanOrEqual(boxes[1]!.y + boxes[1]!.height);
    expect(boxes[2]!.width).toBeCloseTo(boxes[0]!.width, 0);
  } else {
    expect(boxes[1]!.x).toBeGreaterThan(boxes[0]!.x + boxes[0]!.width);
  }
  expect(boxes[3]!.y).toBeGreaterThan(boxes[2]!.y + boxes[2]!.height);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await new AxeBuilder({ page }).analyze()).violations).toEqual([]);
  await focused.screenshot({ path: testInfo.outputPath(`2026-10-06-focused-${width}-${theme}.png`) });
});

for (const width of [1280, 390]) test(`optional form-associated context locks and survives private retries at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto("/evidence-fixture/inventory");
  await page.getByText("Bring in retained evidence", { exact: true }).click();
  await page.getByLabel("Prepared evidence files").setInputFiles({ name: "synthetic-layout-2026-10-06.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ fixture: "SYNTHETIC_INVENTORY_EVIDENCE" })) });
  await page.getByRole("button", { name: "Retain privately", exact: true }).click();
  await page.getByText("Review this discovery", { exact: true }).click();
  await page.getByLabel("How it fits").selectOption("ACTIVE");
  const extras = page.getByText("Work sample and supporting snapshot (optional)", { exact: true });
  await extras.click();
  const link = page.getByLabel("Work sample or workflow link (optional)", { exact: true });
  const snapshot = page.getByRole("combobox", { name: "Supporting snapshot", exact: true });
  await link.fill("https://example.com/synthetic-workflow");
  await snapshot.selectOption("synthetic-raw-evidence");
  await page.getByText("Inspect extracted claims and correct evidence", { exact: true }).click();
  await page.getByRole("button", { name: "Hold next save response", exact: true }).click();
  await page.getByRole("button", { name: "Confirm and save privately", exact: true }).click();
  await expect(link).toBeDisabled();
  await expect(snapshot).toBeDisabled();
  await expect(page.getByRole("textbox", { name: "Corrected observation text", exact: true })).toBeDisabled();
  await page.getByRole("button", { name: "Finish held save", exact: true }).click();
  await expect(page.getByText("Saved privately. Your public profile has not changed.", { exact: true })).toBeVisible();
  await extras.click();
  await expect(link).toHaveValue("https://example.com/synthetic-workflow");
  await expect(snapshot).toHaveValue("synthetic-raw-evidence");
  await snapshot.selectOption("__remove__");
  await page.getByRole("button", { name: "Simulate one lost save response", exact: true }).click();
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await expect(page.getByText("Synthetic lost save response. Retry unchanged decisions.", { exact: true })).toBeVisible();
  await expect(link).toHaveValue("https://example.com/synthetic-workflow");
  await expect(snapshot).toHaveValue("__remove__");
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await expect(page.getByText("Saved supporting snapshot", { exact: true })).toHaveCount(0);
  await extras.click();
  await expect(link).toHaveValue("https://example.com/synthetic-workflow");
  await expect(snapshot).toHaveValue("");
  const operations = (await page.getByLabel("Synthetic save operations").textContent())!.trim().split(/\s+/);
  expect(operations).toHaveLength(3);
  expect(operations[2]).toBe(operations[1]);
  await link.fill("not-a-url");
  await extras.click();
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await expect(link).toBeVisible();
  await expect(link).toBeFocused();
  expect((await page.getByLabel("Synthetic save operations").textContent())!.trim().split(/\s+/)).toHaveLength(3);
  await link.fill("https://example.com/synthetic-workflow");
  await extras.click();
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await expect(page.getByText("Saved privately. Your public profile has not changed.", { exact: true })).toBeVisible();
  await extras.click();
  await expect(link).toHaveValue("https://example.com/synthetic-workflow");
  await page.getByRole("button", { name: "Open synthetic sharing preview", exact: true }).click();
  await expect(page.getByLabel("Synthetic publication status")).toHaveText("Nothing published");
});

for (const width of [1280, 390]) test(`collection cards preserve normal and keyboard-focused appearance in both themes at ${width}px`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto("/evidence-fixture/inventory");
  await page.getByRole("button", { name: "Show card outside collection", exact: true }).click();
  const outside = page.locator('[aria-label="Card outside collection"]').getByRole("article", { name: "Example Tool card", exact: true });
  const inside = page.getByRole("region", { name: "Example Tool in your collection", exact: true }).getByRole("article", { name: "Example Tool card", exact: true });
  const appearance = async (card: typeof inside) => card.evaluate(element => [element, ...element.querySelectorAll("*")].map(node => {
    const style = getComputedStyle(node);
    return [style.backgroundColor, style.color, style.fontFamily, style.fontSize, style.borderColor, style.outlineColor, style.outlineWidth, style.outlineStyle, style.outlineOffset];
  }));
  for (const theme of ["light", "dark"]) {
    await page.getByRole("banner").getByRole("combobox", { name: "Appearance", exact: true }).selectOption(theme);
    await page.getByRole("button", { name: "Show card outside collection", exact: true }).focus();
    await page.mouse.move(0, 0);
    expect(await appearance(inside)).toEqual(await appearance(outside));
    await inside.screenshot({ path: testInfo.outputPath(`2026-10-06-card-normal-${width}-${theme}.png`) });
    const details = inside.getByRole("button", { name: "Details", exact: true });
    await details.focus();
    await page.keyboard.press("Tab");
    await page.keyboard.press("Shift+Tab");
    await expect(details).toBeFocused();
    const focusedAppearance = await appearance(inside);
    await inside.screenshot({ path: testInfo.outputPath(`2026-10-06-card-focused-${width}-${theme}.png`) });
    await outside.getByRole("button", { name: "Details", exact: true }).focus();
    await page.keyboard.press("Tab");
    await page.keyboard.press("Shift+Tab");
    await expect(outside.getByRole("button", { name: "Details", exact: true })).toBeFocused();
    expect(await appearance(outside)).toEqual(focusedAppearance);
  }
});

for (const width of [1280, 390]) test(`observed date remains an editable private draft at ${width}px`, async ({ page }, testInfo) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto("/evidence-fixture/inventory");
  await page.getByText("Review this discovery", { exact: true }).click();
  await page.getByText("Inspect extracted claims and correct evidence", { exact: true }).click();
  const date = page.getByLabel("Started using (optional)", { exact: true });
  const operations = page.getByLabel("Synthetic save operations");
  await page.getByRole("button", { name: "Use this observed date as my start date", exact: true }).click();
  await expect(date).toHaveValue("2024-06-03");
  await expect(operations).toHaveText("");
  await expect(page.getByLabel("Synthetic saved start date")).toHaveText("Unknown");
  await expect(page.getByText("PRIVATE DISCOVERY", { exact: true }).first()).toBeVisible();
  await page.getByRole("region", { name: "Example Tool in your collection", exact: true }).screenshot({ path: testInfo.outputPath(`2026-10-06-observed-date-${width}.png`) });
  await date.fill("2024-05-20");
  await page.getByLabel("How it fits").selectOption("ACTIVE");
  await page.getByRole("button", { name: "Simulate one lost save response", exact: true }).click();
  await page.getByRole("button", { name: "Confirm and save privately", exact: true }).click();
  await expect(page.getByText("Synthetic lost save response. Retry unchanged decisions.", { exact: true })).toBeVisible();
  await expect(date).toHaveValue("2024-05-20");
  await page.getByRole("button", { name: "Confirm and save privately", exact: true }).click();
  await expect(page.getByText("Saved privately. Your public profile has not changed.", { exact: true })).toBeVisible();
  await expect(date).toHaveValue("2024-05-20");
  await expect(page.getByLabel("Synthetic saved start date")).toHaveText("2024-05-20");
  const attempts = (await operations.textContent())!.trim().split(/\s+/);
  expect(attempts).toHaveLength(2);
  expect(attempts[1]).toBe(attempts[0]);
  await date.fill("");
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await expect(date).toHaveValue("");
  await page.getByRole("button", { name: "Open synthetic sharing preview", exact: true }).click();
  await expect(page.getByLabel("Synthetic publication status")).toHaveText("Nothing published");
  await page.getByRole("button", { name: "Load grouped GitHub fixture", exact: true }).click();
  await page.getByText("Review this discovery", { exact: true }).click();
  await page.getByText("Inspect extracted claims and correct evidence", { exact: true }).click();
  await page.getByRole("button", { name: "Use this observed date as my start date", exact: true }).click();
  await page.getByLabel("Record to inspect for GitHub").selectOption("synthetic-github-2");
  await page.getByText("Review this discovery", { exact: true }).click();
  await expect(date).toHaveValue("");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test("an observed-date action is locked during save and a newer saved version clears its draft", async ({ page }) => {
  await page.goto("/evidence-fixture/inventory");
  await page.getByText("Review this discovery", { exact: true }).click();
  await page.getByText("Inspect extracted claims and correct evidence", { exact: true }).click();
  const observed = page.getByRole("button", { name: "Use this observed date as my start date", exact: true });
  const date = page.getByLabel("Started using (optional)", { exact: true });
  await observed.click();
  await page.getByRole("button", { name: "Simulate a newer saved date", exact: true }).click();
  await expect(date).toHaveValue("2025-01-02");
  await expect(page.getByText("Observed date copied to your draft.", { exact: false })).toHaveCount(0);
  await observed.click();
  await page.getByLabel("How it fits").selectOption("TESTING");
  await page.getByRole("button", { name: "Hold next save response", exact: true }).click();
  await page.getByRole("button", { name: "Confirm and save privately", exact: true }).click();
  await expect(observed).toBeDisabled();
  await expect(date).toBeDisabled();
  await page.getByRole("button", { name: "Finish held save", exact: true }).click();
  await expect(observed).toBeEnabled();
  await expect(date).toHaveValue("2024-06-03");
});

for (const width of [1280, 390]) test(`private collection interaction and reversible card at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto("/evidence-fixture/inventory");
  await expect(page.getByText("PRIVATE DISCOVERY", { exact: true }).first()).toBeVisible();
  await page.getByText("Review this discovery", { exact: true }).click();
  await expect(page.getByLabel("How it fits")).toHaveValue("");
  await page.getByLabel("How it fits").selectOption("TESTING");
  await page.getByLabel("Explanation or workflow (optional)", { exact: true }).fill("Trying this for a specific workflow.");
  await page.getByRole("button", { name: "Confirm and save privately" }).click();
  await expect(page.getByText("Manage relationship and context", { exact: true })).toBeVisible();
  await expect(page.getByText("Saved privately. Your public profile has not changed.", { exact: true })).toBeVisible();
  await page.getByLabel("How it fits").selectOption("ACTIVE");
  await page.getByLabel("One of my go-to tools").check();
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await expect(page.getByText("Owner-selected go-to", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Go-to", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Example Tool", exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "History", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Example Tool", exact: true }).first()).toBeVisible();
  const details = page.getByRole("button", { name: "Details", exact: true });
  await details.click();
  await expect(page.locator(".product-card")).toHaveAttribute("data-side", "back");
  await page.keyboard.press("Escape");
  await expect(details).toBeFocused();
  await expect(page.locator(".product-card")).toHaveAttribute("data-side", "front");
  await page.getByLabel("How it fits").selectOption("ARCHIVED");
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await page.getByRole("button", { name: "Go-to", exact: true }).click();
  await expect(page.getByText("No products in this view yet.")).toBeVisible();
  await page.getByRole("button", { name: "Archived", exact: true }).click();
  await page.getByText("Manage relationship and context", { exact: true }).click();
  await page.getByLabel("How it fits").selectOption("ACTIVE");
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await page.getByRole("button", { name: "Current", exact: true }).click();
  await expect(page.getByText("Owner-selected go-to", { exact: true }).first()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const accessibility = await new AxeBuilder({ page }).analyze();
  expect(accessibility.violations).toEqual([]);
});

test("synthetic file import, invalid JSON, and removing a supporting snapshot preserve the retained source", async ({ page }) => {
  await page.goto("/evidence-fixture/inventory");
  await expect(page.getByRole("heading", { name: "Evidence and limitations", exact: true })).toHaveCount(0);
  await page.getByText("Bring in retained evidence", { exact: true }).click();
  await page.getByLabel("Prepared evidence files").setInputFiles({ name: "invalid-synthetic-2026-09-18.json", mimeType: "application/json", buffer: Buffer.from("{not valid JSON}") });
  await page.getByRole("button", { name: "Retain privately", exact: true }).click();
  await expect(page.getByText("Import did not complete.", { exact: false })).toBeVisible();
  await page.getByLabel("Prepared evidence files").setInputFiles({ name: "synthetic-inventory-2026-09-18.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ fixture: "SYNTHETIC_INVENTORY_EVIDENCE" })) });
  await page.getByRole("button", { name: "Retain privately", exact: true }).click();
  await expect(page.getByText("Retained evidence is ready for private review.", { exact: false })).toBeVisible();
  await page.getByText("Review this discovery", { exact: true }).click();
  await page.getByLabel("How it fits").selectOption("ACTIVE");
  await page.getByText("Work sample and supporting snapshot (optional)", { exact: true }).click();
  await page.getByRole("combobox", { name: "Supporting snapshot", exact: true }).selectOption("synthetic-raw-evidence");
  await page.getByRole("button", { name: "Confirm and save privately", exact: true }).click();
  await expect(page.getByText("Saved supporting snapshot", { exact: true })).toBeVisible();
  await page.getByText("Retained snapshot original", { exact: true }).click();
  await expect(page.getByText("SYNTHETIC RETAINED ORIGINAL: seven example contributions.", { exact: true })).toBeVisible();
  await page.getByText("Work sample and supporting snapshot (optional)", { exact: true }).click();
  await page.getByRole("combobox", { name: "Supporting snapshot", exact: true }).selectOption({ label: "Remove saved supporting snapshot" });
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await expect(page.getByText("Saved supporting snapshot", { exact: true })).toHaveCount(0);
  await page.getByText("Work sample and supporting snapshot (optional)", { exact: true }).click();
  await expect(page.getByRole("combobox", { name: "Supporting snapshot", exact: true })).toHaveValue("");
  await expect(page.getByText("Supporting snapshot available for review; it has not replaced your saved card.", { exact: true })).toBeVisible();
  await expect(page.getByText("SYNTHETIC RETAINED ORIGINAL: seven example contributions.", { exact: true })).toBeVisible();
});

test("retrying a lost save response reuses the same operation identity", async ({ page }) => {
  await page.goto("/evidence-fixture/inventory");
  await page.getByText("Review this discovery", { exact: true }).click();
  await page.getByLabel("How it fits").selectOption("TESTING");
  await page.getByLabel("Explanation or workflow (optional)", { exact: true }).fill("Synthetic retry preserves these exact decisions.");
  await page.getByRole("button", { name: "Simulate one lost save response", exact: true }).click();
  await page.getByRole("button", { name: "Confirm and save privately", exact: true }).click();
  await expect(page.getByText("Synthetic lost save response. Retry unchanged decisions.", { exact: true })).toBeVisible();
  await expect(page.getByRole("textbox", { name: "Explanation or workflow (optional)", exact: true })).toHaveValue("Synthetic retry preserves these exact decisions.");
  await page.getByRole("button", { name: "Confirm and save privately", exact: true }).click();
  await expect(page.getByText("Manage relationship and context", { exact: true })).toBeVisible();
  const operations = (await page.getByLabel("Synthetic save operations").textContent())!.trim().split(/\s+/);
  expect(operations).toHaveLength(2);
  expect(operations[1]).toBe(operations[0]);
  await expect(page.getByRole("textbox", { name: "Explanation or workflow (optional)", exact: true })).toHaveValue("Synthetic retry preserves these exact decisions.");
});

test("owner-described product entry needs no website or telemetry and retries without inventing owner decisions", async ({ page }) => {
  await page.goto("/evidence-fixture/inventory");
  await page.getByLabel("Product name", { exact: true }).fill("An occasional tool");
  await expect(page.getByLabel("How do you use it?", { exact: true })).toHaveValue("");
  await page.getByLabel("How do you use it?", { exact: true }).selectOption("LATER");
  await page.getByText("Website or a note (optional)", { exact: true }).click();
  await page.getByLabel("What you want to remember (optional)", { exact: true }).fill("I want to decide how this fits after adding it.");
  await page.getByRole("button", { name: "Simulate one lost add response", exact: true }).click();
  await page.getByRole("button", { name: "Save tool privately", exact: true }).click();
  await expect(page.getByText("Synthetic lost add response. Retry unchanged product.", { exact: true })).toBeVisible();
  await expect(page.getByLabel("Product name", { exact: true })).toHaveValue("An occasional tool");
  await page.getByRole("button", { name: "Save tool privately", exact: true }).click();
  await expect(page.getByText("Saved privately. Review the card", { exact: false })).toBeVisible();
  await expect(page.getByRole("link", { name: "Review your collection", exact: true })).toHaveAttribute("href", "#private-collection-title");
  const operations = (await page.getByLabel("Synthetic add operations").textContent())!.trim().split(/\s+/);
  expect(operations).toHaveLength(2);
  expect(operations[0]).toBe(operations[1]);
  const input = JSON.parse((await page.getByLabel("Synthetic add request").textContent())!);
  expect(input).toMatchObject({ name: "An occasional tool", description: "I want to decide how this fits after adding it." });
  expect(input).not.toHaveProperty("website");
  expect(input).not.toHaveProperty("goTo");
  expect(input).not.toHaveProperty("status");
  expect(input).not.toHaveProperty("activity");
});

test("sharing requires approval of the current exact preview and invalidates it when the collection changes", async ({ page }) => {
  await page.goto("/evidence-fixture/inventory");
  await page.getByRole("button", { name: "Open synthetic sharing preview", exact: true }).click();
  const publish = page.getByRole("button", { name: "Publish this preview", exact: true });
  await expect(publish).toBeDisabled();
  await expect(page.getByText("Only this approved explanation is shared.", { exact: true })).toBeVisible();
  await page.getByLabel("I approve making exactly this preview visible to anyone with the public link.", { exact: true }).check();
  await expect(publish).toBeEnabled();
  await page.getByRole("button", { name: "Simulate changed collection after preview", exact: true }).click();
  await expect(publish).toBeDisabled();
  await expect(page.getByLabel("Synthetic publication status")).toHaveText("Nothing published");
  await expect(page.getByText("Your saved collection or sharing choices changed. Preview again before publishing.", { exact: true })).toBeVisible();
});

for (const width of [1280, 390]) test(`usage stays with its explicitly selected grouped record at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto("/evidence-fixture/inventory");
  await page.getByRole("button", { name: "Load grouped GitHub fixture" }).click();
  const group = page.getByRole("region", { name: "GitHub in your collection", exact: true });
  const selector = group.getByRole("combobox", { name: "Record to inspect for GitHub" });
  await expect(selector).toHaveValue("synthetic-github-1");
  await expect(group.getByText("No usage snapshot is selected for this record. Usage is unknown.", { exact: true })).toBeVisible();
  await expect(group.getByText("1 other loaded record has a saved usage snapshot. Choose it above to inspect its own evidence.", { exact: true })).toBeVisible();
  await expect(selector.getByRole("option", { name: /Record 2 · Usage snapshot/ })).toHaveCount(1);
  await expect(group.locator(".activity-module")).toHaveCount(0);
  await group.getByRole("button", { name: "Details", exact: true }).click();
  await expect(group.locator(".product-card")).toHaveAttribute("data-side", "back");
  await expect(group.locator(".card-back")).not.toContainText("7 contributions");
  await selector.selectOption("synthetic-github-2");
  await expect(group.locator(".product-card")).toHaveAttribute("data-side", "front");
  await expect(group.getByText("This record has a saved usage snapshot. Open Details to see its source and coverage.", { exact: true })).toBeVisible();
  await group.getByRole("button", { name: "Details", exact: true }).click();
  await expect(group.locator(".activity-hero strong")).toHaveText("7");
  await expect(group.locator(".activity-meta")).toContainText("Synthetic retained source");
  await expect(group.locator(".activity-meta")).toContainText("Measurement period not supplied");
  await expect(group.locator(".activity-meta")).toContainText("stale");
  await page.keyboard.press("Escape");
  await expect(group.getByRole("button", { name: "Details", exact: true })).toBeFocused();
  await selector.selectOption("synthetic-github-3");
  await expect(group.getByText("The selected usage snapshot is unavailable. Usage is unknown.", { exact: true })).toBeVisible();
  await expect(group.locator(".activity-module")).toHaveCount(0);
  await selector.selectOption("synthetic-github-1");
  await expect(group.locator(".activity-module")).toHaveCount(0);
  await expect(page.getByLabel("Synthetic save operations")).toHaveText("");
  await page.getByRole("button", { name: "Open synthetic sharing preview", exact: true }).click();
  await expect(page.getByLabel("Synthetic publication status")).toHaveText("Nothing published");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});

// R15: deleting an original takes a second, explicit step.
test("deleting an original asks first, can be cancelled, and removes only that original", async ({ page }) => {
  await page.goto("/evidence-fixture/inventory");
  await page.getByText("Bring in retained evidence", { exact: true }).click();
  await page.getByLabel("Prepared evidence files").setInputFiles({ name: "synthetic-inventory-2026-09-18.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ fixture: "SYNTHETIC_INVENTORY_EVIDENCE" })) });
  await page.getByRole("button", { name: "Retain privately", exact: true }).click();
  await page.getByText("Review this discovery", { exact: true }).click();
  const deletions = page.getByLabel("Synthetic delete operations");

  await page.getByRole("button", { name: "Delete original", exact: true }).click();
  const confirm = page.getByRole("group", { name: "Confirm deleting the original from Synthetic retained source" });
  await expect(confirm).toContainText("can't be restored");
  expect((await new AxeBuilder({ page }).include("main").analyze()).violations).toEqual([]);
  await confirm.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(confirm).toHaveCount(0);
  await expect(deletions).toHaveText("");
  await expect(page.getByText("Synthetic retained source", { exact: true })).toBeVisible();

  await page.getByRole("button", { name: "Delete original", exact: true }).click();
  await page.getByRole("button", { name: "Delete permanently", exact: true }).click();
  await expect(deletions).toHaveText("synthetic-raw-evidence");
  await expect(page.getByText("Deleted the original from Synthetic retained source.", { exact: false })).toBeVisible();
  await expect(page.getByText("Retained snapshot original", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Delete original", exact: true })).toHaveCount(0);
});
