import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

for (const width of [1280, 390]) test(`private collection interaction and reversible card at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto("/evidence-fixture/inventory");
  await expect(page.getByText("PRIVATE DISCOVERY", { exact: true }).first()).toBeVisible();
  await page.getByText("Review this discovery", { exact: true }).click();
  await expect(page.getByLabel("How it fits")).toHaveValue("");
  await page.getByLabel("How it fits").selectOption("TESTING");
  await page.getByLabel("Explanation or workflow (optional)", { exact: true }).fill("Trying this for a specific workflow.");
  await page.getByRole("button", { name: "Confirm and save privately" }).click();
  await expect(page.getByText("Manage relationship and context", { exact: true })).toBeVisible();
  await expect(page.getByText("Saved privately. Your public profile has not changed.", { exact: true })).toBeVisible();
  await page.getByLabel("How it fits").selectOption("ACTIVE");
  await page.getByLabel("One of my go-to tools").check();
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await expect(page.getByText("Owner-selected go-to", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Go-to", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Example Tool", exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "History", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Example Tool", exact: true }).first()).toBeVisible();
  const details = page.getByRole("button", { name: "Details", exact: true });
  await details.click();
  await expect(page.locator(".product-card")).toHaveAttribute("data-side", "back");
  await page.keyboard.press("Escape");
  await expect(details).toBeFocused();
  await expect(page.locator(".product-card")).toHaveAttribute("data-side", "front");
  await page.getByLabel("How it fits").selectOption("ARCHIVED");
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await page.getByRole("button", { name: "Go-to", exact: true }).click();
  await expect(page.getByText("No products in this view yet.")).toBeVisible();
  await page.getByRole("button", { name: "Archived", exact: true }).click();
  await page.getByText("Manage relationship and context", { exact: true }).click();
  await page.getByLabel("How it fits").selectOption("ACTIVE");
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await page.getByRole("button", { name: "Current", exact: true }).click();
  await expect(page.getByText("Owner-selected go-to", { exact: true }).first()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const accessibility = await new AxeBuilder({ page }).analyze();
  expect(accessibility.violations).toEqual([]);
});

test("synthetic file import, invalid JSON, and removing a supporting snapshot preserve the retained source", async ({ page }) => {
  await page.goto("/evidence-fixture/inventory");
  await expect(page.getByRole("heading", { name: "Supporting context", exact: true })).toHaveCount(0);
  await page.getByText("Bring in retained evidence", { exact: true }).click();
  await page.getByLabel("Prepared evidence files").setInputFiles({ name: "invalid-synthetic-2026-09-18.json", mimeType: "application/json", buffer: Buffer.from("{not valid JSON}") });
  await page.getByRole("button", { name: "Retain privately", exact: true }).click();
  await expect(page.getByText("Import did not complete.", { exact: false })).toBeVisible();
  await page.getByLabel("Prepared evidence files").setInputFiles({ name: "synthetic-inventory-2026-09-18.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ fixture: "SYNTHETIC_INVENTORY_EVIDENCE" })) });
  await page.getByRole("button", { name: "Retain privately", exact: true }).click();
  await expect(page.getByText("Retained evidence is ready for private review.", { exact: false })).toBeVisible();
  await page.getByText("Review this discovery", { exact: true }).click();
  await page.getByLabel("How it fits").selectOption("ACTIVE");
  await page.getByRole("combobox", { name: "Supporting snapshot", exact: true }).selectOption("synthetic-raw-evidence");
  await page.getByRole("button", { name: "Confirm and save privately", exact: true }).click();
  await expect(page.getByText("Saved supporting snapshot", { exact: true })).toBeVisible();
  await page.getByText("Retained snapshot original", { exact: true }).click();
  await expect(page.getByText("SYNTHETIC RETAINED ORIGINAL: seven example contributions.", { exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Supporting snapshot", exact: true }).selectOption({ label: "Remove saved supporting snapshot" });
  await page.getByRole("button", { name: "Save privately", exact: true }).click();
  await expect(page.getByText("Saved supporting snapshot", { exact: true })).toHaveCount(0);
  await expect(page.getByRole("combobox", { name: "Supporting snapshot", exact: true })).toHaveValue("");
  await expect(page.getByText("Supporting snapshot available for review; it has not replaced your saved card.", { exact: true })).toBeVisible();
  await expect(page.getByText("SYNTHETIC RETAINED ORIGINAL: seven example contributions.", { exact: true })).toBeVisible();
});

test("retrying a lost save response reuses the same operation identity", async ({ page }) => {
  await page.goto("/evidence-fixture/inventory");
  await page.getByText("Review this discovery", { exact: true }).click();
  await page.getByLabel("How it fits").selectOption("TESTING");
  await page.getByLabel("Explanation or workflow (optional)", { exact: true }).fill("Synthetic retry preserves these exact decisions.");
  await page.getByRole("button", { name: "Simulate one lost save response", exact: true }).click();
  await page.getByRole("button", { name: "Confirm and save privately", exact: true }).click();
  await expect(page.getByText("Synthetic lost save response. Retry unchanged decisions.", { exact: true })).toBeVisible();
  await expect(page.getByRole("textbox", { name: "Explanation or workflow (optional)", exact: true })).toHaveValue("Synthetic retry preserves these exact decisions.");
  await page.getByRole("button", { name: "Confirm and save privately", exact: true }).click();
  await expect(page.getByText("Manage relationship and context", { exact: true })).toBeVisible();
  const operations = (await page.getByLabel("Synthetic save operations").textContent())!.trim().split(/\s+/);
  expect(operations).toHaveLength(2);
  expect(operations[1]).toBe(operations[0]);
  await expect(page.getByRole("textbox", { name: "Explanation or workflow (optional)", exact: true })).toHaveValue("Synthetic retry preserves these exact decisions.");
});

test("owner-described product entry needs no website or telemetry and retries without inventing owner decisions", async ({ page }) => {
  await page.goto("/evidence-fixture/inventory");
  await page.getByLabel("Product name", { exact: true }).fill("An occasional tool");
  await page.getByLabel("What you want to remember (optional)", { exact: true }).fill("I want to decide how this fits after adding it.");
  await page.getByRole("button", { name: "Simulate one lost add response", exact: true }).click();
  await page.getByRole("button", { name: "Add for private review", exact: true }).click();
  await expect(page.getByText("Synthetic lost add response. Retry unchanged product.", { exact: true })).toBeVisible();
  await expect(page.getByLabel("Product name", { exact: true })).toHaveValue("An occasional tool");
  await page.getByRole("button", { name: "Add for private review", exact: true }).click();
  await expect(page.getByText("Saved privately. Review the card", { exact: false })).toBeVisible();
  await expect(page.getByRole("link", { name: "Review your card", exact: true })).toHaveAttribute("href", "#private-collection-title");
  const operations = (await page.getByLabel("Synthetic add operations").textContent())!.trim().split(/\s+/);
  expect(operations).toHaveLength(2);
  expect(operations[0]).toBe(operations[1]);
  const input = JSON.parse((await page.getByLabel("Synthetic add request").textContent())!);
  expect(input).toMatchObject({ name: "An occasional tool", description: "I want to decide how this fits after adding it." });
  expect(input).not.toHaveProperty("website");
  expect(input).not.toHaveProperty("goTo");
  expect(input).not.toHaveProperty("status");
  expect(input).not.toHaveProperty("activity");
});

test("sharing requires approval of the current exact preview and invalidates it when the collection changes", async ({ page }) => {
  await page.goto("/evidence-fixture/inventory");
  await page.getByRole("button", { name: "Open synthetic sharing preview", exact: true }).click();
  const publish = page.getByRole("button", { name: "Publish this preview", exact: true });
  await expect(publish).toBeDisabled();
  await expect(page.getByText("Only this approved explanation is shared.", { exact: true })).toBeVisible();
  await page.getByLabel("I approve making exactly this preview visible to anyone with the public link.", { exact: true }).check();
  await expect(publish).toBeEnabled();
  await page.getByRole("button", { name: "Simulate changed collection after preview", exact: true }).click();
  await expect(publish).toBeDisabled();
  await expect(page.getByLabel("Synthetic publication status")).toHaveText("Nothing published");
  await expect(page.getByText("Your saved collection or sharing choices changed. Preview again before publishing.", { exact: true })).toBeVisible();
});

for (const width of [1280, 390]) test(`usage stays with its explicitly selected grouped record at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.goto("/evidence-fixture/inventory");
  await page.getByRole("button", { name: "Load grouped GitHub fixture" }).click();
  const group = page.getByRole("region", { name: "GitHub in your collection", exact: true });
  const selector = group.getByRole("combobox", { name: "Record to inspect for GitHub" });
  await expect(selector).toHaveValue("synthetic-github-1");
  await expect(group.getByText("No usage snapshot is selected for this record. Usage is unknown.", { exact: true })).toBeVisible();
  await expect(group.getByText("1 other loaded record has a saved usage snapshot. Choose it above to inspect its own evidence.", { exact: true })).toBeVisible();
  await expect(selector.getByRole("option", { name: /Record 2 · Usage snapshot/ })).toHaveCount(1);
  await expect(group.locator(".activity-module")).toHaveCount(0);
  await group.getByRole("button", { name: "Details", exact: true }).click();
  await expect(group.locator(".product-card")).toHaveAttribute("data-side", "back");
  await expect(group.locator(".card-back")).not.toContainText("7 contributions");
  await selector.selectOption("synthetic-github-2");
  await expect(group.locator(".product-card")).toHaveAttribute("data-side", "front");
  await expect(group.getByText("This record has a saved usage snapshot. Open Details to see its source and coverage.", { exact: true })).toBeVisible();
  await group.getByRole("button", { name: "Details", exact: true }).click();
  await expect(group.locator(".activity-hero strong")).toHaveText("7");
  await expect(group.locator(".activity-meta")).toContainText("Synthetic retained source");
  await expect(group.locator(".activity-meta")).toContainText("Measurement period not supplied");
  await expect(group.locator(".activity-meta")).toContainText("stale");
  await page.keyboard.press("Escape");
  await expect(group.getByRole("button", { name: "Details", exact: true })).toBeFocused();
  await selector.selectOption("synthetic-github-3");
  await expect(group.getByText("The selected usage snapshot is unavailable. Usage is unknown.", { exact: true })).toBeVisible();
  await expect(group.locator(".activity-module")).toHaveCount(0);
  await selector.selectOption("synthetic-github-1");
  await expect(group.locator(".activity-module")).toHaveCount(0);
  await expect(page.getByLabel("Synthetic save operations")).toHaveText("");
  await page.getByRole("button", { name: "Open synthetic sharing preview", exact: true }).click();
  await expect(page.getByLabel("Synthetic publication status")).toHaveText("Nothing published");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
