#!/usr/bin/env node
// Outside review by Claude: the parts of .github/workflows/claude-review.yml
// that don't need a model.
// - prepare: reads the pull request, refuses one that Claude wrote or helped
//   write (the model that wrote a PR never clears it), and writes the files
//   Claude reads.
// - post: turns Claude's structured output into one review of the commit. The
//   review's last line is a structured receipt for owner inspection, never
//   automatic merge clearance.
// Claude itself only reads. The rules are in docs/remediation/CODEX-BRIEF.md,
// Section 4, "Review policy".

import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { buildContext } from "../.github/claude-review/context.mjs";
import process from "node:process";
import { pathToFileURL } from "node:url";

export const CLAUDE_BOT = "claude[bot]";
// GitHub credits commits from Claude Code's address to the "claude" account,
// and the Claude app acts as claude[bot].
export const CLAUDE_LOGINS = [CLAUDE_BOT, "claude"];
export const CLAUDE_EMAILS = ["noreply@anthropic.com"];
export const CLAUDE_BRANCH_PREFIX = "claude/";
// GitHub lists at most 250 commits for a pull request. A list that long may be
// cut short, so it can't show who wrote the rest.
export const MAX_COMMITS = 250;
export const SEVERITIES = ["P0", "P1"];
// Skips the owner hears about in the pull request. Closed and fork PRs are
// only logged.
export const NOTIFY_SKIPS = ["base", "pins", "context", "writer", "too-long", "no-token", "moved"];
const CO_AUTHOR = /^co-authored-by:\s*claude\b/im;
// What Claude Code leaves in commit messages and PR descriptions: its
// "Generated with [Claude Code]" or "Generated by [Claude Code]" footer, a
// claude.ai/code session link, or a Claude-Session trailer.
const CLAUDE_MARKS = /generated (?:with|by) \[claude code\]|claude\.ai\/code\/session_|^claude-session:/im;
// GitHub refuses a review or comment body over 65,536 characters.
const MAX_BODY = 60_000;
const MARKER = /^<!-- claude-review verdict=(clean|findings|none) sha=([0-9a-f]{40}) run=(\d+) -->$/;
// Credential shapes a review must never carry: GitHub tokens, Anthropic keys
// and OAuth tokens, and JSON Web Tokens such as the runner's.
const CREDENTIAL_PATTERNS = [
  /\bgh[pousr]_[A-Za-z0-9]{30,}/,
  /\bgithub_pat_[A-Za-z0-9_]{30,}/,
  /\bsk-ant-[A-Za-z0-9_-]{20,}/,
  /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\./,
];
const LIMITS = { summary: 4000, field: 1500, file: 300, findings: 30, notes: 20, note: 500 };

export function createGitHub(token, repo) {
  async function request(path, { method = "GET", body } = {}) {
    const response = await fetch(`https://api.github.com${path.replace("{repo}", repo)}`, {
      method,
      headers: {
        accept: "application/vnd.github+json",
        authorization: `Bearer ${token}`,
        "x-github-api-version": "2022-11-28",
        ...(body ? { "content-type": "application/json" } : {}),
      },
      body: body ? JSON.stringify(body) : undefined,
    });
    const text = await response.text();
    const data = text ? JSON.parse(text) : null;
    if (!response.ok) {
      const error = new Error(`${method} ${path} returned ${response.status}: ${data?.message ?? text.slice(0, 200)}`);
      error.status = response.status;
      throw error;
    }
    return data;
  }
  // Every page, or an error: a partial list never passes for the whole.
  async function all(path, pages = 50) {
    const items = [];
    for (let page = 1; page <= pages; page += 1) {
      const separator = path.includes("?") ? "&" : "?";
      const batch = await request(`${path}${separator}per_page=100&page=${page}`);
      items.push(...batch);
      if (batch.length < 100) return items;
    }
    throw new Error(`${path.replace("{repo}", repo)} lists more than ${pages * 100} entries`);
  }
  return { request, all };
}

// Evidence that Claude wrote or helped write the pull request. Any one is
// enough to refuse, so a false match only sends the PR to another reviewer:
// a Claude branch; a PR opened by a Claude account; a description with Claude
// Code's footer or session link; a commit by a Claude account or address; or a
// commit message with a Claude co-author trailer, footer or session link.
export function claudeEvidence(pull, commits) {
  const evidence = [];
  // Git allows a backtick in a branch name, and one would end the code span.
  if ((pull.head?.ref ?? "").startsWith(CLAUDE_BRANCH_PREFIX)) evidence.push(`branch \`${pull.head.ref.replace(/`/g, "")}\``);
  if (CLAUDE_LOGINS.includes(pull.user?.login)) evidence.push(`opened by ${pull.user.login}`);
  if (CLAUDE_MARKS.test(pull.body ?? "")) evidence.push("a Claude Code footer or session link in the description");
  for (const commit of commits) {
    const sha = commit.sha.slice(0, 7);
    const logins = [commit.author?.login, commit.committer?.login];
    const emails = [commit.commit?.author?.email, commit.commit?.committer?.email].map(email => email?.toLowerCase());
    const message = commit.commit?.message ?? "";
    const login = CLAUDE_LOGINS.find(name => logins.includes(name));
    if (login) evidence.push(`commit ${sha} by ${login}`);
    else if (CLAUDE_EMAILS.some(email => emails.includes(email))) evidence.push(`commit ${sha} from Claude Code's address`);
    else if (CO_AUTHOR.test(message)) evidence.push(`commit ${sha} co-authored by Claude`);
    else if (CLAUDE_MARKS.test(message)) evidence.push(`commit ${sha} with a Claude Code footer or session link`);
  }
  return evidence;
}

const SHA = /^[0-9a-f]{40}$/;

// Owner pins are data, never shell fragments. Existing main-based requests
// may omit them; stacked requests must name both exact commits.
export function requestedPins(head = "", base = "") {
  if ((head || base) && (!SHA.test(head) || !SHA.test(base))) throw new Error("Both review pins must be full commit SHAs.");
  return { expectedHeadSha: head, expectedBaseSha: base };
}

export async function currentReview({ github, repo, number, context }) {
  const [pull, main] = await Promise.all([
    github.request(`/repos/{repo}/pulls/${number}`),
    github.request("/repos/{repo}/git/ref/heads/main"),
  ]);
  const changed = [
    pull.state !== "open" && "pull request closed",
    pull.head?.repo?.full_name !== repo && "head repository changed",
    pull.base?.repo?.full_name !== repo && "base repository changed",
    pull.head?.sha !== context.headSha && "head changed",
    pull.head?.ref !== context.headRef && "head branch changed",
    pull.base?.sha !== context.baseSha && "base commit changed",
    pull.base?.ref !== context.baseRef && "base branch changed",
    main.object?.sha !== context.mainSha && "trusted main changed",
    claudeEvidence(pull, []).length > 0 && "Claude writer evidence changed",
  ].filter(Boolean);
  return { pull, ok: changed.length === 0, reason: changed.join("; ") };
}

export async function prepare({ github, repo, number, dir, hasToken, mainSha,
  repositoryDir, expectedHeadSha = "", expectedBaseSha = "", contextBuilder = buildContext }) {
  const pull = await github.request(`/repos/{repo}/pulls/${number}`);
  if (pull.state !== "open") return { skip: "closed", note: `#${number} is closed, so Claude won't review it.` };
  if (pull.head?.repo?.full_name !== repo || pull.base?.repo?.full_name !== repo) {
    return { skip: "fork", note: `#${number} has a head or base outside this repository, so Claude won't review it here.` };
  }
  const sha = pull.head.sha;
  const stop = (skip, note) => ({ skip, sha, note });
  if (![sha, pull.base.sha, mainSha].every(value => SHA.test(value ?? ""))) {
    return stop("base", "Review requires full immutable head, base and trusted-main revisions.");
  }
  if (pull.base.ref === "main" && pull.base.sha !== mainSha) return stop("moved", "Trusted main moved; request a fresh review job.");
  if (((expectedHeadSha || expectedBaseSha) && (expectedHeadSha !== sha || expectedBaseSha !== pull.base.sha)) ||
    (pull.base.ref !== "main" && (!expectedHeadSha || !expectedBaseSha))) {
    return stop("pins", `Review #${number} requires matching owner dispatch inputs: head_sha=${sha}, base_sha=${pull.base.sha}.`);
  }
  const commits = await github.all(`/repos/{repo}/pulls/${number}/commits`, 3);
  if (commits.length >= MAX_COMMITS) return stop("too-long", "Too many commits to verify complete independent authorship; no review started.");
  const writer = evidence => stop("writer", `Claude won't review #${number}: Claude wrote or helped write it (${evidence.join("; ")}). ` +
    "The model that wrote a PR never clears it. Ask the owner to appoint an independent reviewer other than Claude.");
  const evidence = claudeEvidence(pull, commits);
  if (pull.base.ref.startsWith(CLAUDE_BRANCH_PREFIX)) evidence.push("a Claude dependency branch");
  if (evidence.length) return writer(evidence);
  if (!hasToken) return stop("no-token", "Claude can't review yet: the `CLAUDE_CODE_OAUTH_TOKEN` secret is missing from the `reviewers` environment. " +
    "Report this to the owner; creating or replacing credentials needs separate authorization (docs/remediation/CODEX-BRIEF.md, Section 9).");

  let context;
  try {
    context = await contextBuilder({ repositoryDir, reviewDir: dirname(dir), headSha: sha, baseSha: pull.base.sha, mainSha, baseRef: pull.base.ref });
  } catch (error) {
    const reason = quotesCredential(String(error.message), []) ? "unsafe diagnostic withheld" : safe(String(error.message), { oneLine: true });
    return stop("context", `Review context could not be prepared safely: ${reason}. No model was started.`);
  }
  if (context.commitShas.length >= MAX_COMMITS) return stop("too-long", "Introduced dependency history exceeds the authorship review limit.");
  const known = new Map(commits.map(commit => [commit.sha, commit]));
  const introduced = [];
  for (const commitSha of context.commitShas) {
    const commit = known.get(commitSha) ?? await github.request(`/repos/{repo}/commits/${commitSha}`);
    if (commit.sha !== commitSha) return stop("context", "Commit metadata does not match the pinned dependency history.");
    introduced.push(commit);
  }
  const dependencyEvidence = claudeEvidence(pull, introduced);
  if (dependencyEvidence.length) return writer(dependencyEvidence);
  const expected = { ...context, number, repo, headRef: pull.head.ref, baseRef: pull.base.ref };
  const current = await currentReview({ github, repo, number, context: expected });
  if (!current.ok) return stop("moved", `Review context changed while preparing #${number}: ${current.reason}. Ask again.`);
  const summary = { ...expected, title: current.pull.title, body: current.pull.body ?? "", author: current.pull.user?.login ?? null };
  writeFileSync(join(dir, "pr.json"), `${JSON.stringify(summary, null, 2)}\n`);
  writeFileSync(join(dir, "commits.txt"), introduced.map(commit => `commit ${commit.sha}\n\n${commit.commit?.message ?? ""}\n`).join("\n"));
  return { sha, baseSha: context.baseSha, manifestDigest: context.manifestDigest,
    note: `Prepared #${number} head ${sha}, base ${context.baseSha}, ancestor ${context.ancestorSha}, trusted main ${mainSha}; ${introduced.length} introduced commits.` };
}

export function loadContext(dir, digest, repo, number) {
  if (!dir || !/^[0-9a-f]{64}$/.test(digest ?? "")) throw new Error("Pinned review context and manifest digest are required");
  const bytes = readFileSync(join(dir, "trees.json"));
  if (createHash("sha256").update(bytes).digest("hex") !== digest) throw new Error("Review context manifest changed");
  const manifest = JSON.parse(bytes);
  const context = JSON.parse(readFileSync(join(dir, "pr.json"), "utf8"));
  if (context.repo !== repo || context.number !== number || context.manifestDigest !== digest || context.baseRef !== manifest.baseRef ||
    ["headSha", "baseSha", "mainSha", "ancestorSha"].some(key => !SHA.test(context[key] ?? "") || context[key] !== manifest[key])) {
    throw new Error("Review context does not match its pinned manifest or PR");
  }
  return context;
}

const text = value => (typeof value === "string" ? value.trim() : "");
const clip = (value, limit) => (value.length > limit ? `${value.slice(0, limit - 1)}…` : value);

// Claude reads pinned trees by absolute path. Strip only the known context
// prefixes; a nested repository folder named pr-head remains a real path.
function repoPath(value, workspace = "") {
  const file = text(value).replace(/^\.\//, "");
  const underHead = file.match(/^(?:\/.*?\/claude-review\/)?(?:pr-head|pr-base|dependency-base)\/(.+)$/)?.[1];
  if (underHead) return underHead;
  const root = `${workspace.replace(/\/+$/, "")}/`;
  return root !== "/" && file.startsWith(root) ? file.slice(root.length) : file;
}

// The fields of the workflow's --json-schema, and no others.
const REVIEW_KEYS = ["verdict", "summary", "findings", "notes"];
const FINDING_KEYS = ["severity", "file", "line", "problem", "why", "fix", "revision"];
const REVISIONS = ["head", "base", "ancestor"];
const pathRevision = file => ({ "pr-head": "head", "pr-base": "base", "dependency-base": "ancestor" })[text(file).match(/^(?:\/.*?\/claude-review\/)?(pr-head|pr-base|dependency-base)\//)?.[1]];
const onlyKeys = (value, keys) => Object.keys(value).every(key => keys.includes(key));

function validFinding(finding, workspace) {
  if (!finding || typeof finding !== "object" || Array.isArray(finding) || !onlyKeys(finding, FINDING_KEYS)) return false;
  if (![finding.file, finding.problem, finding.why, finding.fix].every(value => typeof value === "string")) return false;
  const file = repoPath(finding.file, workspace);
  const lineOk = finding.line === undefined || (Number.isInteger(finding.line) && finding.line > 0);
  const revisionOk = finding.revision === undefined || (REVISIONS.includes(finding.revision) && (!pathRevision(finding.file) || pathRevision(finding.file) === finding.revision));
  return revisionOk && SEVERITIES.includes(finding.severity) && Boolean(file) && file.length <= LIMITS.file &&
    !file.startsWith("/") && !file.split("/").includes("..") && Boolean(text(finding.problem)) && lineOk;
}

const cleanFinding = (finding, workspace) => ({
  severity: finding.severity,
  file: repoPath(finding.file, workspace),
  ...((finding.revision ?? pathRevision(finding.file)) && (finding.revision ?? pathRevision(finding.file)) !== "head"
    ? { revision: finding.revision ?? pathRevision(finding.file) } : {}),
  line: Number.isInteger(finding.line) ? finding.line : null,
  problem: clip(text(finding.problem), LIMITS.field),
  why: clip(text(finding.why), LIMITS.field),
  fix: clip(text(finding.fix), LIMITS.field),
});

const none = reason => ({ verdict: "none", reason, summary: "", findings: [], notes: [] });

// Claude's structured output, read strictly. Clean needs Claude to say
// "clean" and list no findings. Any listed finding wins over the word.
// Anything missing, malformed or unfinished is no verdict, which clears
// nothing. The workspace is main's checkout, where Claude runs.
export function readVerdict(raw, conclusion = "success", workspace = "") {
  if (conclusion !== "success") return none(`Claude didn't finish (${conclusion || "no result"})`);
  if (!raw) return none("Claude finished without a verdict");
  let output;
  try {
    output = JSON.parse(raw);
  } catch {
    return none("Claude's verdict wasn't valid JSON");
  }
  if (!output || typeof output !== "object" || Array.isArray(output)) return none("Claude's verdict wasn't an object");
  // Every field the schema asks for, with its type, and nothing more. A
  // malformed answer is no verdict; nothing gets filled in or dropped.
  const shaped = onlyKeys(output, REVIEW_KEYS) && ["clean", "findings"].includes(output.verdict) &&
    typeof output.summary === "string" && Array.isArray(output.findings) &&
    Array.isArray(output.notes) && output.notes.every(note => typeof note === "string");
  if (!shaped) return none("Claude's answer didn't match the review format");
  if (!output.findings.every(finding => validFinding(finding, workspace))) return none("Claude's findings were malformed");
  // The review lists at most LIMITS.findings, but counts every one.
  const total = output.findings.length;
  const findings = output.findings.slice(0, LIMITS.findings).map(finding => cleanFinding(finding, workspace));
  const summary = clip(text(output.summary), LIMITS.summary);
  const notes = output.notes.map(text).filter(Boolean).slice(0, LIMITS.notes).map(note => clip(note, LIMITS.note));
  if (findings.length) return { verdict: "findings", summary, findings, notes, total };
  if (output.verdict === "clean") return { verdict: "clean", summary, findings, notes, total };
  return none("Claude answered \"findings\" without listing any");
}

// Model text goes into the review as plain text. Its HTML, entities, links,
// images and code spans are escaped, so nothing can pass for the verdict line
// or load from elsewhere. Each paragraph is one line that can't open a
// heading, list or quote. Any whitespace-free chunk GitHub could turn into a
// link or a ping (a web address, an @ or # before a letter or digit, or what
// it reads as a commit SHA or a GH- reference) goes whole in a code span of
// our own, so nothing next to it gains an edge to link on.
const LINKABLE = /@[0-9a-z]|#[0-9a-z]|:\/\/|www\.|mailto:|xmpp:|(?<![0-9a-z])(?:gh-\d|[0-9a-f]{7,40}(?![0-9a-z]))/i;
const ENTITIES = { "&": "&amp;", "<": "&lt;", ">": "&gt;" };

// Fenced with more backticks than the chunk holds, padded when it starts or
// ends with one, as CommonMark reads code spans.
function codeSpan(chunk) {
  const fence = "`".repeat(Math.max(0, ...(chunk.match(/`+/g) ?? []).map(run => run.length)) + 1);
  const pad = chunk.startsWith("`") || chunk.endsWith("`") ? " " : "";
  return `${fence}${pad}${chunk}${pad}${fence}`;
}

function safe(value, { oneLine = false } = {}) {
  return (oneLine ? [value] : value.split(/\n\s*\n/))
    .map(paragraph => paragraph.replace(/\s+/g, " ").trim())
    .filter(Boolean)
    .map(paragraph => paragraph.split(" ")
      .map(chunk => (LINKABLE.test(chunk) ? codeSpan(chunk) : chunk.replace(/[\\`[\]&<>]/g, char => ENTITIES[char] ?? `\\${char}`)))
      .join(" ")
      .replace(/^[#+*=_~|-]/, "\\$&")
      .replace(/^(\d+)([.)])/, "$1\\$2"))
    .join("\n\n");
}

// encodeURIComponent leaves parentheses alone, and an unbalanced one would end
// the Markdown link early.
const pathPart = part => encodeURIComponent(part).replace(/[()]/g, char => `%${char.charCodeAt(0).toString(16).toUpperCase()}`);
const blobLink = (repo, sha, file, line) =>
  `https://github.com/${repo}/blob/${sha}/${file.split("/").map(pathPart).join("/")}${line ? `#L${line}` : ""}`;

export function reviewBody({ result, sha, runId, repo, context = null }) {
  const count = result.total ?? result.findings.length;
  const title = { clean: "clean", findings: `${count} finding${count === 1 ? "" : "s"}`, none: "no verdict" }[result.verdict];
  const head = [`### Claude review of \`${sha.slice(0, 7)}\`: ${title}`, ""];
  if (result.verdict === "none") head.push(`${safe(result.reason, { oneLine: true })}. This review clears nothing.`, "");
  if (result.summary) head.push(safe(result.summary), "");
  const findings = result.findings.map((finding, index) => {
    // The path sits in a code span, so only a backtick or a line break could
    // end it early.
    const where = (finding.line ? `${finding.file}:${finding.line}` : finding.file).replace(/[`\r\n]/g, "");
    const parts = [safe(finding.problem, { oneLine: true })];
    if (finding.why) parts.push(safe(finding.why, { oneLine: true }));
    if (finding.fix) parts.push(`Fix: ${safe(finding.fix, { oneLine: true })}`);
    return `${index + 1}. **${finding.severity}** [\`${where}\`](${blobLink(repo, finding.revision === "base" ? context.baseSha : finding.revision === "ancestor" ? context.ancestorSha : sha, finding.file, finding.line)}): ${parts.join(" ")}`;
  });
  const notes = result.notes.length
    ? ["<details><summary>Notes that don't block</summary>", "", ...result.notes.map(note => `- ${safe(note, { oneLine: true })}`), "", "</details>", ""]
    : [];
  // Required review evidence still needs owner verification: marker text does
  // not establish provenance or protect against instructions in PR text.
  const tail = [
    ...(context ? [`Pinned context: main \`${context.mainSha}\`; dependency ancestor \`${context.ancestorSha}\`; base \`${context.baseSha}\`; head \`${sha}\`.`,
      `Context manifest SHA-256: \`${context.manifestDigest ?? "unavailable"}\`.`, ""] : []),
    `<sub>Outside review by Claude in [run ${runId}](https://github.com/${repo}/actions/runs/${runId}). ` +
      "Required independent review; the owner must verify exact-head evidence and passing CI before authorizing landing. A clean verdict does not authorize an automatic merge. Claude only reads, and the model that wrote a PR never clears it.</sub>",
    `<!-- claude-review verdict=${result.verdict} sha=${sha} run=${runId} -->`,
  ];
  const assemble = (shown, withNotes) => {
    const lines = [...head, ...findings.slice(0, shown)];
    // Findings past the listing cap or the body limit are counted, never lost.
    const hidden = count - shown;
    if (hidden) lines.push(`${hidden} more finding${hidden === 1 ? "" : "s"} didn't fit in one review.`);
    if (count) lines.push("");
    return [...lines, ...(withNotes ? notes : []), ...tail].join("\n");
  };
  // Keep under GitHub's body limit: notes go first, then the last findings.
  // The verdict and the count in the title always cover every finding.
  let shown = findings.length;
  let body = assemble(shown, true);
  if (body.length > MAX_BODY) body = assemble(shown, false);
  while (body.length > MAX_BODY && shown > 1) {
    shown -= 1;
    body = assemble(shown, false);
  }
  return body;
}

// The verdict a review body carries, read from its last line only, so text
// quoted above it can't pass for one.
export function verdictMarker(body) {
  const last = String(body ?? "").trimEnd().split("\n").at(-1) ?? "";
  const match = last.match(MARKER);
  return match ? { verdict: match[1], sha: match[2], run: Number(match[3]) } : null;
}

// Whether Claude's answer quotes a credential, by its shape or by the exact
// value of a secret this job holds. Claude reads files a PR's author chose, so
// a planted instruction could steer it toward one. The answer is checked as
// sent and as decoded, since a JSON \u escape hides a token from the first.
// This is a backstop: the read fence keeps Claude away from the secrets.
export function quotesCredential(raw, secrets = []) {
  const forms = [String(raw ?? "")];
  try {
    forms.push(JSON.stringify(JSON.parse(raw)));
  } catch {
    // Not JSON: no decoded form, and readVerdict posts none of it anyway.
  }
  return forms.some(value => CREDENTIAL_PATTERNS.some(pattern => pattern.test(value)) ||
    secrets.some(secret => typeof secret === "string" && secret.length >= 8 && value.includes(secret)));
}

export async function post({ github, repo, number, sha, runId, raw, conclusion, secrets = [], workspace = "", context = null }) {
  // Nothing Claude wrote is posted when it quotes a credential.
  let result = quotesCredential(raw, secrets)
    ? none("Claude's answer quoted what looks like a credential, so none of it was posted")
    : readVerdict(raw, conclusion, workspace);
  if (context) {
    if (context.headSha !== sha || context.number !== number) throw new Error("Posted review does not match the prepared PR/head");
    let current;
    try { current = await currentReview({ github, repo, number, context }); }
    catch { current = { ok: false, reason: "context could not be revalidated" }; }
    if (!current.ok) {
      const reason = `Review context changed: ${current.reason}; this is historical evidence, not current clearance`;
      if (result.verdict === "clean") result = none(reason);
      else if (result.verdict === "findings") result = { ...result, notes: [reason, ...result.notes] };
    }
  } else if (result.findings.some(finding => finding.revision)) {
    result = none("Base/ancestor finding has no pinned review context");
  }
  const body = reviewBody({ result, sha, runId, repo, context });
  try {
    await github.request(`/repos/{repo}/pulls/${number}/reviews`, { method: "POST", body: { commit_id: sha, event: "COMMENT", body } });
    return { verdict: result.verdict, where: "review" };
  } catch (error) {
    if (error.status !== 422) throw error;
    // A force-push can race the last identity check. Rejected review creation
    // cannot fall back to a clean comment for a possibly detached commit.
    if (context && result.verdict === "clean") result = none("GitHub refused the pinned review; request a fresh review of the current context");
    const fallback = reviewBody({ result, sha, runId, repo, context });
    await github.request(`/repos/{repo}/issues/${number}/comments`, { method: "POST", body: { body: fallback } });
    return { verdict: result.verdict, where: "comment" };
  }
}

// Claude's answer, read from the action's log of the run. An environment
// variable can't carry it: Linux won't start a step whose environment holds a
// string of 128 KiB or more, and that would lose even the no-verdict review.
// Only a successful final result counts; anything else is no answer.
export function answerFrom(executionFile) {
  let messages;
  try {
    messages = JSON.parse(readFileSync(executionFile, "utf8"));
  } catch {
    return "";
  }
  const result = Array.isArray(messages) ? messages.findLast(message => message?.type === "result") : null;
  const output = result?.structured_output;
  if (result?.subtype !== "success" || result.is_error !== false || !output || typeof output !== "object") return "";
  return JSON.stringify(output);
}

export async function main(argv = process.argv.slice(2), env = process.env, log = console.log, github = null) {
  const [command] = argv;
  const repo = env.GITHUB_REPOSITORY;
  const number = Number(env.PR_NUMBER);
  if (!repo || !Number.isInteger(number) || number < 1) throw new Error("GITHUB_REPOSITORY and a positive PR_NUMBER are required");
  const api = github ?? createGitHub(env.GITHUB_TOKEN, repo);
  const output = (key, value) => {
    if (env.GITHUB_OUTPUT) appendFileSync(env.GITHUB_OUTPUT, `${key}=${value}\n`);
  };
  if (command === "prepare") {
    if (!env.REVIEW_CONTEXT_DIR) throw new Error("REVIEW_CONTEXT_DIR is required");
    const pins = requestedPins(env.EXPECTED_HEAD_SHA ?? "", env.EXPECTED_BASE_SHA ?? "");
    const result = await prepare({ github: api, repo, number, dir: env.REVIEW_CONTEXT_DIR, hasToken: env.HAS_CLAUDE_TOKEN === "true",
      mainSha: env.GITHUB_SHA, repositoryDir: env.GITHUB_WORKSPACE, ...pins });
    log(result.note);
    output("sha", result.sha ?? "");
    output("skip", result.skip ?? "");
    output("manifest_digest", result.manifestDigest ?? "");
    if (NOTIFY_SKIPS.includes(result.skip)) {
      await api.request(`/repos/{repo}/issues/${number}/comments`, { method: "POST", body: { body: result.note } });
    }
    return result;
  }
  if (command === "check") {
    const context = loadContext(env.REVIEW_CONTEXT_DIR, env.MANIFEST_DIGEST, repo, number);
    const current = await currentReview({ github: api, repo, number, context });
    output("ready", current.ok ? "true" : "false");
    if (!current.ok) {
      const note = `Claude did not run: review context changed (${current.reason}). Request fresh review with current pins.`;
      log(note);
      await api.request(`/repos/{repo}/issues/${number}/comments`, { method: "POST", body: { body: note } });
    }
    return current;
  }
  if (command === "post") {
    if (!/^[0-9a-f]{40}$/.test(env.HEAD_SHA ?? "")) throw new Error("HEAD_SHA must be a full commit SHA");
    if (!/^\d+$/.test(env.GITHUB_RUN_ID ?? "")) throw new Error("GITHUB_RUN_ID is required");
    const result = await post({
      github: api, repo, number, sha: env.HEAD_SHA, runId: env.GITHUB_RUN_ID,
      raw: env.EXECUTION_FILE ? answerFrom(env.EXECUTION_FILE) : "", conclusion: env.CLAUDE_CONCLUSION,
      secrets: [env.GITHUB_TOKEN, env.CLAUDE_CODE_OAUTH_TOKEN], workspace: env.GITHUB_WORKSPACE ?? "",
      context: loadContext(env.REVIEW_CONTEXT_DIR, env.MANIFEST_DIGEST, repo, number),
    });
    log(`Claude's verdict on ${env.HEAD_SHA.slice(0, 7)}: ${result.verdict}, posted as a ${result.where}.`);
    return result;
  }
  throw new Error(`Unknown command "${command ?? ""}". Use prepare, check or post.`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  main().catch(error => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
