#!/usr/bin/env node
// Outside review by Claude: the parts of .github/workflows/claude-review.yml
// that don't need a model.
// - prepare: reads the pull request, refuses one that Claude wrote or helped
//   write (the model that wrote a PR never clears it), and writes the files
//   Claude reads.
// - post: turns Claude's structured output into one review of the commit. The
//   review's last line is a verdict the autopilot can check.
// Claude itself only reads. The rules are in docs/remediation/CODEX-BRIEF.md,
// Section 4, "Review policy".

import { appendFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { pathToFileURL } from "node:url";

export const CLAUDE_BOT = "claude[bot]";
// GitHub credits commits from Claude Code's address to the "claude" account,
// and the Claude app acts as claude[bot].
export const CLAUDE_LOGINS = [CLAUDE_BOT, "claude"];
export const CLAUDE_EMAILS = ["noreply@anthropic.com"];
export const CLAUDE_BRANCH_PREFIX = "claude/";
// GitHub lists at most 250 commits for a pull request. A list that long may be
// cut short, so it can't show who wrote the rest.
export const MAX_COMMITS = 250;
export const SEVERITIES = ["P0", "P1"];
// Skips the owner hears about in the pull request. Closed and fork PRs are
// only logged.
export const NOTIFY_SKIPS = ["base", "writer", "too-long", "no-token", "moved"];
const CO_AUTHOR = /^co-authored-by:\s*claude\b/im;
// What Claude Code leaves in commit messages and PR descriptions: its
// "Generated with [Claude Code]" or "Generated by [Claude Code]" footer, a
// claude.ai/code session link, or a Claude-Session trailer.
const CLAUDE_MARKS = /generated (?:with|by) \[claude code\]|claude\.ai\/code\/session_|^claude-session:/im;
// GitHub refuses a review or comment body over 65,536 characters.
const MAX_BODY = 60_000;
const MARKER = /^<!-- claude-review verdict=(clean|findings|none) sha=([0-9a-f]{40}) run=(\d+) -->$/;
// Credential shapes a review must never carry: GitHub tokens, Anthropic keys
// and OAuth tokens, and JSON Web Tokens such as the runner's.
const CREDENTIAL_PATTERNS = [
  /\bgh[pousr]_[A-Za-z0-9]{30,}/,
  /\bgithub_pat_[A-Za-z0-9_]{30,}/,
  /\bsk-ant-[A-Za-z0-9_-]{20,}/,
  /\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\./,
];
const LIMITS = { summary: 4000, field: 1500, file: 300, findings: 30, notes: 20, note: 500 };

export function createGitHub(token, repo) {
  async function request(path, { method = "GET", body } = {}) {
    const response = await fetch(`https://api.github.com${path.replace("{repo}", repo)}`, {
      method,
      headers: {
        accept: "application/vnd.github+json",
        authorization: `Bearer ${token}`,
        "x-github-api-version": "2022-11-28",
        ...(body ? { "content-type": "application/json" } : {}),
      },
      body: body ? JSON.stringify(body) : undefined,
    });
    const text = await response.text();
    const data = text ? JSON.parse(text) : null;
    if (!response.ok) {
      const error = new Error(`${method} ${path} returned ${response.status}: ${data?.message ?? text.slice(0, 200)}`);
      error.status = response.status;
      throw error;
    }
    return data;
  }
  // Every page, or an error: a partial list never passes for the whole.
  async function all(path, pages = 50) {
    const items = [];
    for (let page = 1; page <= pages; page += 1) {
      const separator = path.includes("?") ? "&" : "?";
      const batch = await request(`${path}${separator}per_page=100&page=${page}`);
      items.push(...batch);
      if (batch.length < 100) return items;
    }
    throw new Error(`${path.replace("{repo}", repo)} lists more than ${pages * 100} entries`);
  }
  return { request, all };
}

// Evidence that Claude wrote or helped write the pull request. Any one is
// enough to refuse, so a false match only sends the PR to another reviewer:
// a Claude branch; a PR opened by a Claude account; a description with Claude
// Code's footer or session link; a commit by a Claude account or address; or a
// commit message with a Claude co-author trailer, footer or session link.
export function claudeEvidence(pull, commits) {
  const evidence = [];
  // Git allows a backtick in a branch name, and one would end the code span.
  if (pull.head.ref.startsWith(CLAUDE_BRANCH_PREFIX)) evidence.push(`branch \`${pull.head.ref.replace(/`/g, "")}\``);
  if (CLAUDE_LOGINS.includes(pull.user?.login)) evidence.push(`opened by ${pull.user.login}`);
  if (CLAUDE_MARKS.test(pull.body ?? "")) evidence.push("a Claude Code footer or session link in the description");
  for (const commit of commits) {
    const sha = commit.sha.slice(0, 7);
    const logins = [commit.author?.login, commit.committer?.login];
    const emails = [commit.commit?.author?.email, commit.commit?.committer?.email].map(email => email?.toLowerCase());
    const message = commit.commit?.message ?? "";
    const login = CLAUDE_LOGINS.find(name => logins.includes(name));
    if (login) evidence.push(`commit ${sha} by ${login}`);
    else if (CLAUDE_EMAILS.some(email => emails.includes(email))) evidence.push(`commit ${sha} from Claude Code's address`);
    else if (CO_AUTHOR.test(message)) evidence.push(`commit ${sha} co-authored by Claude`);
    else if (CLAUDE_MARKS.test(message)) evidence.push(`commit ${sha} with a Claude Code footer or session link`);
  }
  return evidence;
}

const fileSection = file => [
  `=== ${file.filename} (${file.status}, +${file.additions} -${file.deletions})` +
    (file.previous_filename ? `, renamed from ${file.previous_filename}` : ""),
  file.patch ?? "(GitHub sent no patch: the file is binary or its diff is too large. The PR's version is under pr-head/, unless the PR removes the file. Main's version, if it has one, is in the working directory; a removal that merges cleanly removes exactly that.)",
  "",
].join("\n");

export async function prepare({ github, repo, number, dir, hasToken }) {
  const pull = await github.request(`/repos/{repo}/pulls/${number}`);
  if (pull.state !== "open") return { skip: "closed", note: `#${number} is ${pull.state}, so Claude won't review it.` };
  if (pull.head?.repo?.full_name !== repo) {
    return { skip: "fork", note: `#${number} comes from another repository, so Claude won't review it here.` };
  }
  const sha = pull.head.sha;
  // Claude reads main as the PR's base: the working directory, and a removed
  // file's content when GitHub sends no patch.
  if (pull.base?.ref !== "main") {
    const base = String(pull.base?.ref ?? "").replace(/`/g, "");
    return { skip: "base", sha, note: `Claude won't review #${number}: it targets \`${base}\`, not main, and the review reads main as the base.` };
  }
  const commits = await github.all(`/repos/{repo}/pulls/${number}/commits`, 3);
  if (commits.length >= MAX_COMMITS) {
    return { skip: "too-long", sha, note: `Claude won't review #${number}: it has ${commits.length} or more commits, too many to check who wrote them. Review it by hand.` };
  }
  const writer = evidence => ({
    skip: "writer",
    sha,
    note: `Claude won't review #${number}: Claude wrote or helped write it (${evidence.join("; ")}). ` +
      "The model that wrote a PR never clears it. Ask Codex instead: `@codex review`.",
  });
  const evidence = claudeEvidence(pull, commits);
  if (evidence.length) return writer(evidence);
  if (!hasToken) {
    return {
      skip: "no-token",
      sha,
      note: "Claude can't review yet: the `CLAUDE_CODE_OAUTH_TOKEN` secret is missing. Run `claude setup-token`, " +
        "then add the token to the `reviewers` environment (docs/remediation/CODEX-BRIEF.md, Section 9).",
    };
  }
  const files = await github.all(`/repos/{repo}/pulls/${number}/files`, 30);
  // A push while the lists were read would mix two commits: the writer check,
  // the diff and the checked-out tree must all describe the same one. The PR
  // must also still be open, from this repository, and into the same main.
  const again = await github.request(`/repos/{repo}/pulls/${number}`);
  const changed = [
    again.head?.sha !== sha && `${sha.slice(0, 7)} to ${String(again.head?.sha ?? "unknown").slice(0, 7)}`,
    again.state !== "open" && `now ${String(again.state ?? "unknown").replace(/[^a-z]/gi, "")}`,
    again.head?.repo?.full_name !== repo && "now from another repository",
    again.base?.ref !== "main" && `now into \`${String(again.base?.ref ?? "unknown").replace(/`/g, "")}\``,
    again.base?.ref === "main" && again.base?.sha !== pull.base?.sha &&
      `base ${String(pull.base?.sha ?? "unknown").slice(0, 7)} to ${String(again.base?.sha ?? "unknown").slice(0, 7)}`,
  ].filter(Boolean);
  if (changed.length) {
    return {
      skip: "moved",
      sha,
      note: `Claude didn't review #${number}: it changed while Claude was reading it (${changed.join("; ")}). Ask again.`,
    };
  }
  // The title, description and branch can change without a push, so the
  // writer check runs again on the second look, and Claude reads them as of it.
  const later = claudeEvidence(again, commits);
  if (later.length) return writer(later);
  mkdirSync(dir, { recursive: true });
  const summary = {
    number,
    title: again.title,
    body: again.body ?? "",
    author: again.user?.login ?? null,
    headRef: again.head.ref,
    headSha: sha,
    baseRef: again.base.ref,
  };
  writeFileSync(join(dir, "pr.json"), `${JSON.stringify(summary, null, 2)}\n`);
  writeFileSync(join(dir, "commits.txt"), commits.map(commit => `commit ${commit.sha}\n\n${commit.commit?.message ?? ""}\n`).join("\n"));
  writeFileSync(join(dir, "diff.patch"), files.map(fileSection).join("\n"));
  return { sha, note: `Reviewing ${sha.slice(0, 7)} of #${number}: ${files.length} files, ${commits.length} commits.` };
}

const text = value => (typeof value === "string" ? value.trim() : "");
const clip = (value, limit) => (value.length > limit ? `${value.slice(0, limit - 1)}…` : value);

// Claude reads the PR's files under .../claude-review/pr-head/, so it may name
// them that way. Findings name paths from the repository root, so only that
// checkout prefix goes: a folder of the repository named pr-head stays.
function repoPath(value) {
  const file = text(value).replace(/^\.\//, "");
  return file.match(/^(?:\/.*?\/claude-review\/)?pr-head\/(.+)$/)?.[1] ?? file;
}

// The fields of the workflow's --json-schema, and no others.
const REVIEW_KEYS = ["verdict", "summary", "findings", "notes"];
const FINDING_KEYS = ["severity", "file", "line", "problem", "why", "fix"];
const onlyKeys = (value, keys) => Object.keys(value).every(key => keys.includes(key));

function validFinding(finding) {
  if (!finding || typeof finding !== "object" || Array.isArray(finding) || !onlyKeys(finding, FINDING_KEYS)) return false;
  if (![finding.file, finding.problem, finding.why, finding.fix].every(value => typeof value === "string")) return false;
  const file = repoPath(finding.file);
  const lineOk = finding.line === undefined || (Number.isInteger(finding.line) && finding.line > 0);
  return SEVERITIES.includes(finding.severity) && Boolean(file) && file.length <= LIMITS.file &&
    !file.startsWith("/") && !file.split("/").includes("..") && Boolean(text(finding.problem)) && lineOk;
}

const cleanFinding = finding => ({
  severity: finding.severity,
  file: repoPath(finding.file),
  line: Number.isInteger(finding.line) ? finding.line : null,
  problem: clip(text(finding.problem), LIMITS.field),
  why: clip(text(finding.why), LIMITS.field),
  fix: clip(text(finding.fix), LIMITS.field),
});

const none = reason => ({ verdict: "none", reason, summary: "", findings: [], notes: [] });

// Claude's structured output, read strictly. Clean needs Claude to say
// "clean" and list no findings. Any listed finding wins over the word.
// Anything missing, malformed or unfinished is no verdict, which clears
// nothing.
export function readVerdict(raw, conclusion = "success") {
  if (conclusion !== "success") return none(`Claude didn't finish (${conclusion || "no result"})`);
  if (!raw) return none("Claude finished without a verdict");
  let output;
  try {
    output = JSON.parse(raw);
  } catch {
    return none("Claude's verdict wasn't valid JSON");
  }
  if (!output || typeof output !== "object" || Array.isArray(output)) return none("Claude's verdict wasn't an object");
  // Every field the schema asks for, with its type, and nothing more. A
  // malformed answer is no verdict; nothing gets filled in or dropped.
  const shaped = onlyKeys(output, REVIEW_KEYS) && ["clean", "findings"].includes(output.verdict) &&
    typeof output.summary === "string" && Array.isArray(output.findings) &&
    Array.isArray(output.notes) && output.notes.every(note => typeof note === "string");
  if (!shaped) return none("Claude's answer didn't match the review format");
  if (!output.findings.every(validFinding)) return none("Claude's findings were malformed");
  // The review lists at most LIMITS.findings, but counts every one.
  const total = output.findings.length;
  const findings = output.findings.slice(0, LIMITS.findings).map(cleanFinding);
  const summary = clip(text(output.summary), LIMITS.summary);
  const notes = output.notes.map(text).filter(Boolean).slice(0, LIMITS.notes).map(note => clip(note, LIMITS.note));
  if (findings.length) return { verdict: "findings", summary, findings, notes, total };
  if (output.verdict === "clean") return { verdict: "clean", summary, findings, notes, total };
  return none("Claude answered \"findings\" without listing any");
}

// Model text goes into the review as plain text. Its HTML, entities, links,
// images and code spans are escaped, so nothing can pass for the verdict line
// or load from elsewhere. Each paragraph is one line that can't open a
// heading, list or quote. Any whitespace-free chunk GitHub could turn into a
// link or a ping (a web address, an @ or # before a letter or digit, or what
// it reads as a commit SHA or a GH- reference) goes whole in a code span of
// our own, so nothing next to it gains an edge to link on.
const LINKABLE = /@[0-9a-z]|#[0-9a-z]|:\/\/|www\.|mailto:|xmpp:|(?<![0-9a-z])(?:gh-\d|[0-9a-f]{7,40}(?![0-9a-z]))/i;
const ENTITIES = { "&": "&amp;", "<": "&lt;", ">": "&gt;" };

// Fenced with more backticks than the chunk holds, padded when it starts or
// ends with one, as CommonMark reads code spans.
function codeSpan(chunk) {
  const fence = "`".repeat(Math.max(0, ...(chunk.match(/`+/g) ?? []).map(run => run.length)) + 1);
  const pad = chunk.startsWith("`") || chunk.endsWith("`") ? " " : "";
  return `${fence}${pad}${chunk}${pad}${fence}`;
}

function safe(value, { oneLine = false } = {}) {
  return (oneLine ? [value] : value.split(/\n\s*\n/))
    .map(paragraph => paragraph.replace(/\s+/g, " ").trim())
    .filter(Boolean)
    .map(paragraph => paragraph.split(" ")
      .map(chunk => (LINKABLE.test(chunk) ? codeSpan(chunk) : chunk.replace(/[\\`[\]&<>]/g, char => ENTITIES[char] ?? `\\${char}`)))
      .join(" ")
      .replace(/^[#+*=_~|-]/, "\\$&")
      .replace(/^(\d+)([.)])/, "$1\\$2"))
    .join("\n\n");
}

const blobLink = (repo, sha, file, line) =>
  `https://github.com/${repo}/blob/${sha}/${file.split("/").map(encodeURIComponent).join("/")}${line ? `#L${line}` : ""}`;

export function reviewBody({ result, sha, runId, repo }) {
  const count = result.total ?? result.findings.length;
  const title = { clean: "clean", findings: `${count} finding${count === 1 ? "" : "s"}`, none: "no verdict" }[result.verdict];
  const head = [`### Claude review of \`${sha.slice(0, 7)}\`: ${title}`, ""];
  if (result.verdict === "none") head.push(`${safe(result.reason, { oneLine: true })}. This review clears nothing.`, "");
  if (result.summary) head.push(safe(result.summary), "");
  const findings = result.findings.map((finding, index) => {
    // The path sits in a code span, so only a backtick or a line break could
    // end it early.
    const where = (finding.line ? `${finding.file}:${finding.line}` : finding.file).replace(/[`\r\n]/g, "");
    const parts = [safe(finding.problem, { oneLine: true })];
    if (finding.why) parts.push(safe(finding.why, { oneLine: true }));
    if (finding.fix) parts.push(`Fix: ${safe(finding.fix, { oneLine: true })}`);
    return `${index + 1}. **${finding.severity}** [\`${where}\`](${blobLink(repo, sha, finding.file, finding.line)}): ${parts.join(" ")}`;
  });
  const notes = result.notes.length
    ? ["<details><summary>Notes that don't block</summary>", "", ...result.notes.map(note => `- ${safe(note, { oneLine: true })}`), "", "</details>", ""]
    : [];
  // A PR's own text can steer any model that reads it, so this verdict is
  // advisory until the owner decides how an AI verdict may count.
  const tail = [
    `<sub>Outside review by Claude in [run ${runId}](https://github.com/${repo}/actions/runs/${runId}). ` +
      "Advisory: nothing merges on this verdict yet. Claude only reads, and the model that wrote a PR never clears it.</sub>",
    `<!-- claude-review verdict=${result.verdict} sha=${sha} run=${runId} -->`,
  ];
  const assemble = (shown, withNotes) => {
    const lines = [...head, ...findings.slice(0, shown)];
    // Findings past the listing cap or the body limit are counted, never lost.
    const hidden = count - shown;
    if (hidden) lines.push(`${hidden} more finding${hidden === 1 ? "" : "s"} didn't fit in one review.`);
    if (count) lines.push("");
    return [...lines, ...(withNotes ? notes : []), ...tail].join("\n");
  };
  // Keep under GitHub's body limit: notes go first, then the last findings.
  // The verdict and the count in the title always cover every finding.
  let shown = findings.length;
  let body = assemble(shown, true);
  if (body.length > MAX_BODY) body = assemble(shown, false);
  while (body.length > MAX_BODY && shown > 1) {
    shown -= 1;
    body = assemble(shown, false);
  }
  return body;
}

// The verdict a review body carries, read from its last line only, so text
// quoted above it can't pass for one.
export function verdictMarker(body) {
  const last = String(body ?? "").trimEnd().split("\n").at(-1) ?? "";
  const match = last.match(MARKER);
  return match ? { verdict: match[1], sha: match[2], run: Number(match[3]) } : null;
}

// Whether Claude's answer quotes a credential, by its shape or by the exact
// value of a secret this job holds. Claude reads files a PR's author chose, so
// a planted instruction could steer it toward one. The answer is checked as
// sent and as decoded, since a JSON \u escape hides a token from the first.
// This is a backstop: the read fence keeps Claude away from the secrets.
export function quotesCredential(raw, secrets = []) {
  const forms = [String(raw ?? "")];
  try {
    forms.push(JSON.stringify(JSON.parse(raw)));
  } catch {
    // Not JSON: no decoded form, and readVerdict posts none of it anyway.
  }
  return forms.some(value => CREDENTIAL_PATTERNS.some(pattern => pattern.test(value)) ||
    secrets.some(secret => typeof secret === "string" && secret.length >= 8 && value.includes(secret)));
}

export async function post({ github, repo, number, sha, runId, raw, conclusion, secrets = [] }) {
  // Nothing Claude wrote is posted when it quotes a credential.
  const result = quotesCredential(raw, secrets)
    ? none("Claude's answer quoted what looks like a credential, so none of it was posted")
    : readVerdict(raw, conclusion);
  const body = reviewBody({ result, sha, runId, repo });
  try {
    await github.request(`/repos/{repo}/pulls/${number}/reviews`, { method: "POST", body: { commit_id: sha, event: "COMMENT", body } });
    return { verdict: result.verdict, where: "review" };
  } catch (error) {
    if (error.status !== 422) throw error;
    // GitHub refuses a review of a commit the PR no longer contains, as after
    // a force-push. The verdict still names its commit, so post it as a comment.
    await github.request(`/repos/{repo}/issues/${number}/comments`, { method: "POST", body: { body } });
    return { verdict: result.verdict, where: "comment" };
  }
}

// Claude's answer, read from the action's log of the run. An environment
// variable can't carry it: Linux won't start a step whose environment holds a
// string of 128 KiB or more, and that would lose even the no-verdict review.
// Only a successful final result counts; anything else is no answer.
export function answerFrom(executionFile) {
  let messages;
  try {
    messages = JSON.parse(readFileSync(executionFile, "utf8"));
  } catch {
    return "";
  }
  const result = Array.isArray(messages) ? messages.findLast(message => message?.type === "result") : null;
  const output = result?.structured_output;
  if (result?.subtype !== "success" || result.is_error !== false || !output || typeof output !== "object") return "";
  return JSON.stringify(output);
}

export async function main(argv = process.argv.slice(2), env = process.env, log = console.log, github = null) {
  const [command] = argv;
  const repo = env.GITHUB_REPOSITORY;
  const number = Number(env.PR_NUMBER);
  if (!repo || !Number.isInteger(number) || number < 1) throw new Error("GITHUB_REPOSITORY and a positive PR_NUMBER are required");
  const api = github ?? createGitHub(env.GITHUB_TOKEN, repo);
  const output = (key, value) => {
    if (env.GITHUB_OUTPUT) appendFileSync(env.GITHUB_OUTPUT, `${key}=${value}\n`);
  };
  if (command === "prepare") {
    if (!env.REVIEW_CONTEXT_DIR) throw new Error("REVIEW_CONTEXT_DIR is required");
    const result = await prepare({ github: api, repo, number, dir: env.REVIEW_CONTEXT_DIR, hasToken: env.HAS_CLAUDE_TOKEN === "true" });
    log(result.note);
    output("sha", result.sha ?? "");
    output("skip", result.skip ?? "");
    if (NOTIFY_SKIPS.includes(result.skip)) {
      await api.request(`/repos/{repo}/issues/${number}/comments`, { method: "POST", body: { body: result.note } });
    }
    return result;
  }
  if (command === "post") {
    if (!/^[0-9a-f]{40}$/.test(env.HEAD_SHA ?? "")) throw new Error("HEAD_SHA must be a full commit SHA");
    if (!/^\d+$/.test(env.GITHUB_RUN_ID ?? "")) throw new Error("GITHUB_RUN_ID is required");
    const result = await post({
      github: api, repo, number, sha: env.HEAD_SHA, runId: env.GITHUB_RUN_ID,
      raw: env.EXECUTION_FILE ? answerFrom(env.EXECUTION_FILE) : "", conclusion: env.CLAUDE_CONCLUSION,
      secrets: [env.GITHUB_TOKEN, env.CLAUDE_CODE_OAUTH_TOKEN],
    });
    log(`Claude's verdict on ${env.HEAD_SHA.slice(0, 7)}: ${result.verdict}, posted as a ${result.where}.`);
    return result;
  }
  throw new Error(`Unknown command "${command ?? ""}". Use prepare or post.`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  main().catch(error => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
